from . import karibu_product
from . import karibu_location
from . import karibu_export
from . import karibu_truck_line
from . import incentive_order
from . import product_template
from . import fleet_vehicle
from . import res_partner
from . import res_company
from . import purchase_order
