{
    'name': 'NT Purchase',
    'version': '19.0.1.3.0',
    'category': 'Inventory/Purchase',
    'summary': 'NorthStar purchase customisations: incentives, truck details and Karibu Portal LPO export',
    'author': 'NorthStar Technologies International Ltd.',
    'depends': ['purchase_stock', 'nt_stock'],
    'external_dependencies': {'python': ['openpyxl']},
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/ir_sequence_data.xml',
        'data/karibu_product_data.xml',
        'wizard/incentive_order_wizard_views.xml',
        'wizard/incentive_import_wizard_views.xml',
        'views/incentive_order_views.xml',
        'views/karibu_views.xml',
        'views/purchase_order_views.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
